name: sanqing
description: 三清工具
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.5

flutter:
  assets:
    - assets/bg.mp4
    - assets/bg_end.png
