name: sanqing
description: 三清工具
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.0

flutter:
  assets:
    - assets/bg.mp4
    - assets/bg_end.png
