- name: 创建全新Flutter项目并打包
  run: |
    flutter create -t app new_app
    cp -r lib new_app/
    cp pubspec.yaml new_app/
    if [ -d assets ]; then cp -r assets new_app/; fi
    # 复制你提前写好的安卓res资源（图标、样式xml）
    cp -r android/app/src/main/res new_app/android/app/src/main/
    cd new_app
    flutter pub get
    flutter build apk --release
- name: 上传APK安装包
  uses: actions/upload-artifact@v4
  with:
    name: app-release安装包
    path: new_app/build/app/outputs/apk/release/app-release.apk
